from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "output" / "pdf"
OUTPUT.mkdir(parents=True, exist_ok=True)


def build_report(filename: str, title: str, subtitle: str, metrics: list[tuple[str, str]], rows: list[list[str]], note: str):
    path = OUTPUT / filename
    doc = SimpleDocTemplate(
        str(path),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=title,
        author="Enable",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#111827"),
        spaceAfter=4 * mm,
    )
    muted = ParagraphStyle(
        "Muted",
        parent=styles["BodyText"],
        fontSize=9,
        leading=14,
        textColor=colors.HexColor("#6B7280"),
    )
    section = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#111827"),
        spaceBefore=6 * mm,
        spaceAfter=3 * mm,
    )
    body = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=9,
        leading=14,
        textColor=colors.HexColor("#374151"),
    )

    story = [
        Paragraph("ENABLE / CONTROLLED REPORT", muted),
        Spacer(1, 3 * mm),
        Paragraph(title, title_style),
        Paragraph(subtitle, muted),
        Spacer(1, 8 * mm),
    ]

    metric_table = Table([[Paragraph(label, muted), Paragraph(value, section)] for label, value in metrics], colWidths=[55 * mm, 105 * mm])
    metric_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F7F7F8")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.extend([metric_table, Paragraph("Review details", section)])

    detail_table = Table(rows, repeatRows=1, colWidths=[45 * mm, 40 * mm, 75 * mm])
    detail_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))
    story.extend([
        detail_table,
        Paragraph("Control note", section),
        Paragraph(note, body),
        Spacer(1, 12 * mm),
        Paragraph("Generated by Enable for prototype review. Values are simulated.", muted),
    ])
    doc.build(story)


build_report(
    "BIS-Risk-Asset-Report-October-2026.pdf",
    "BIS Risk Asset Report",
    "October 2026 | Ready for approval",
    [("Confirmed risk asset value", "742.6M"), ("Authorized source", "Approved Risk Ledger"), ("Validation status", "Passed")],
    [
        ["Control", "Result", "Evidence"],
        ["Source authorization", "Passed", "Approved Risk Ledger"],
        ["Workbook comparison", "0.7M variance", "Reporting workbook: 741.9M"],
        ["Approver review", "Required", "Comment must be recorded"],
    ],
    "The report uses the confirmed authorized ledger value. External submission has not started.",
)

build_report(
    "Daily-Cash-Flow-Reconciliation-October-2026-Report.pdf",
    "Daily Cash Flow Reconciliation",
    "October 2026 | Ready for approval",
    [("Transactions matched", "2,184"), ("Source files", "3 of 3 verified"), ("Unresolved breaks", "0")],
    [
        ["Source", "Status", "Evidence"],
        ["Daily cash ledger", "Verified", "Daily_Cash_Ledger_2026-10-04.xlsx"],
        ["Custodian confirmation", "Verified", "Custodian_Cash_Confirmation.msg"],
        ["Treasury approval", "Verified", "Treasury_Adjustment_Approval.msg"],
    ],
    "All required source files are available. Approval completes the run; no external delivery will occur.",
)
